<a href="https://colab.research.google.com/github/riddhimach24-dev/Data_Science/blob/main/02_Pandas/Pandas_day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas - Class 3: Data Cleaning Essentials
Welcome to **Class 3** of our Pandas series. Today we’ll learn how to clean and prepare data for analysis.

## Handling Missing Values
Real-world datasets often have missing data. Pandas offers:
- `isna()` / `isnull()` → detect missing values (returns True/False)
- `dropna()` → remove missing values (rows/columns)
- `fillna()` → replace missing values with a given value or method (e.g., forward fill)

Always inspect how much data is missing before deciding to drop or fill.

In [ ]:
import pandas as pd
import numpy as np
a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, None, 35, 40, None],
    "City": ["Delhi", "Mumbai", None, "Bangalore", "Chennai"],
    "Score": [85, 91, np.nan, 88, 95]
}

b = pd.DataFrame(a)
print(b)

#1. null values in dataframe will be return to boolean
print(b.isna().sum())  # .sum counting no. of null values

#isnull
print(b.isnull().sum())  #both of them do the same thing

#2. drop null values (remove complete rows/columns which have null values)
print(b.dropna()) #not prefrerable much in datascience

#3. #fillna
b['City'] = b['City'].fillna('unknown')
b   #"unknown" is filled where we need to fill char value

#
b['Score'] = b['Score'].fillna(b['Score'].mean())
b   #"mean,mode...."are filled where need to fill int value

b['Age'] = b['Age'].fillna(b['Age'].median())
b

# fill null value
b['City'].fillna(b['City'].mode())  #jo city bohot baar repeat hui hai
b['City'].fillna('unknown' , inplace = True) #placeholder
b['Score'].fillna(0, inplace = True)
b['Age'].fillna(b['Age'].mean(), inplace = True) #fill the mean value the null value

      Name   Age       City  Score
0    Alice  25.0      Delhi   85.0
1      Bob   NaN     Mumbai   91.0
2  Charlie  35.0       None    NaN
3    David  40.0  Bangalore   88.0
4     Emma   NaN    Chennai   95.0
Name     0
Age      2
City     1
Score    1
dtype: int64
Name     0
Age      2
City     1
Score    1
dtype: int64
    Name   Age       City  Score
0  Alice  25.0      Delhi   85.0
3  David  40.0  Bangalore   88.0

/tmp/ipykernel_1260/570595617.py:35: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  b['City'].fillna('unknown' , inplace = True) #placeholder
/tmp/ipykernel_1260/570595617.py:36: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  b['Score'].fillna(0, inplace = True)
/tmp/ipykernel_1260/570595617.py:37: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  b['Age'].fillna(b['Age'].mean(), inplace = True) #fill the mean value the null value

## Changing Data Types (`astype`)
- Convert a column to a different type using `astype()`.
- Examples: converting strings to numbers, integers to floats, or columns to category.

Be careful: make sure the data is compatible with the new type!

In [ ]:
a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "Score": [88, 92, 79, 85, 95]
}

b = pd.DataFrame(a)
b.dtypes


b['Age'] = b['Age'].astype(str)
b.dtypes

b['Score'] = b['Score'].astype('category')
b.dtypes

b['Name'] =b['Name'].replace('David' , 'Suresh')
print(b)

      Name Age Score
0    Alice  25    88
1      Bob  30    92
2  Charlie  35    79
3   Suresh  40    85
4     Emma  22    95

## Replacing Values (`replace`)
- Use `replace()` to substitute specific values or patterns.
- Useful for cleaning labels, fixing typos, or mapping categories.

In [ ]:
data = {
    "City": ["Bhopal", "Indore", "Bhopal", "Ujjain"]
}

df = pd.DataFrame(data)
# Replace "Bhopal" with "Sehore"
df["City"] = df["City"].replace("Bhopal", "Mumbai")
print(df)

df['City'] = df['City'].replace("Indore", "indore")
print(df)

     City
0  Mumbai
1  Indore
2  Mumbai
3  Ujjain
     City
0  Mumbai
1  indore
2  Mumbai
3  Ujjain

## Dropping Rows & Columns (`drop`)
- `drop(labels, axis=0)` → drop rows by index labels.
- `drop(labels, axis=1)` → drop columns by name.
- Use `inplace=True` if you want to modify the DataFrame directly.

In [ ]:
# Drop a row
import pandas as pd

df = pd.DataFrame({
    "Name": ["Aman", "Riya", "Vikas"],
    "Age": [20, 21, 22]
})

# Row with index 1 remove
df = df.drop(1)

    Name  Age
0   Aman   20
2  Vikas   22

In [ ]:
# Drop a column
a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "Score": [88, 92, 79, 85, 95]
}

b = pd.DataFrame(a)
print(b)

b.drop(['Age' ,'Score'], axis = 1)

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

      Name
0    Alice
1      Bob
2  Charlie
3    David
4     Emma

In [ ]:
# Modify dataframe
df = pd.DataFrame({
    "Name": ["Aman", "Riya", "Vikas"],
    "Age": [20, 21, 22]
})

# Directly modify DataFrame
df.drop("Age", axis=1, inplace=True)

print(df)

## Detecting & Removing Duplicates
- `duplicated()` → returns a Boolean Series marking duplicate rows.
- `drop_duplicates()` → remove duplicate rows.
- You can specify `subset` (columns) and `keep` ('first', 'last', or False).

In [11]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "Alice", "Bob", "David"],
    "Age": [25, 30, 35, 25, 30, 40],
    "Score": [88, 92, 79, 88, 92, 85]
}

df = pd.DataFrame(data)

print(df)
print(df.duplicated().sum())
df.drop_duplicates()
df.drop_duplicates(subset = 'Name' , keep = 'last')

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    Alice   25     88
4      Bob   30     92
5    David   40     85
2

      Name  Age  Score
2  Charlie   35     79
3    Alice   25     88
4      Bob   30     92
5    David   40     85

## Mini Practice
1. Create a messy DataFrame with missing values, wrong data types, typos, extra columns, and duplicates.
2. Clean it step-by-step using what you learned:
   - Handle missing values
   - Change data types
   - Replace incorrect values
   - Drop unnecessary rows/columns
   - Remove duplicates

In [16]:
import pandas as pd
import numpy as np

# 1. Create a messy DataFrame
data = {
    "Name": ["Alice", "Bob", "Chrlie", "David", "Alice", None],
    "Age": ["25", "30", None, "40", "25", "30"],      # ages stored as strings, with missing value
    "City": ["Delhi", "Mumbai", "Pun", "Bangalore", "Delhi", "Mumbai"],  # typo: "Pun" -> "Pune"
    "Score": [85, None, 78, 88, 85, 91],              # missing value in Score
    "Extra": ["x", "y", "z", "x", "y", "z"]           # extra column we don't really need
}

df = pd.DataFrame(data)

print("Original messy DataFrame:")
print(df)

# 2. Handle missing values
# Fill or drop as needed
df['Name'] = df['Name'].fillna("Helena")
df['Age'] = df['Age'].fillna('32')
df['Score'] = df['Score'].fillna(df['Score'].mean())
df

# 3. Change data types
# Convert Age to int, Score to float, etc.
df['Age'] = df['Age'].astype(int)
df['Score'] = df['Score'].astype(float)
df

# 4. Replace incorrect values
# Fix 'Pun' -> 'Pune', maybe unify Name spellings if needed
df['City'] = df['City'].replace('Pun', 'Pune')
df
# 5. Drop unnecessary rows/columns
# Remove 'Extra' or any row you don't want
df = df.drop(['Extra'], axis=1)
df


# 6. Remove duplicates
# Use duplicated() and drop_duplicates()
df.duplicated().sum()
df = df.drop_duplicates(subset= 'Name' ,keep= 'first')
df

df = df.set_index('Name')

# 7. Final clean DataFrame
# Print the cleaned DataFrame and check info()
print("Final Cleaned DataFrame:")
print(df)
print(df.info())

Original messy DataFrame:
     Name   Age       City  Score Extra
0   Alice    25      Delhi   85.0     x
1     Bob    30     Mumbai    NaN     y
2  Chrlie  None        Pun   78.0     z
3   David    40  Bangalore   88.0     x
4   Alice    25      Delhi   85.0     y
5    None    30     Mumbai   91.0     z
Final Cleaned DataFrame:
        Age       City  Score
Name
Alice    25      Delhi   85.0
Bob      30     Mumbai   85.4
Chrlie   32       Pune   78.0
David    40  Bangalore   88.0
Helena   30     Mumbai   91.0
<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Alice to Helena
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     5 non-null      int64
 1   City    5 non-null      object
 2   Score   5 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 160.0+ bytes
None

---
## Summary
- Learned to handle missing values (`isna`, `dropna`, `fillna`).
- Converted column data types with `astype`.
- Cleaned up incorrect entries with `replace`.
- Removed unwanted rows/columns with `drop`.
- Detected and removed duplicates.