<a href="https://colab.research.google.com/github/riddhimach24-dev/Data_Science/blob/main/02_Pandas/Pandas_day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas - Class 2: DataFrame Basics
Welcome to **Class 2**. Today we’ll learn how to **inspect**, **select**, and **organize** data inside a DataFrame.

## 1 Inspecting Data
Quick ways to understand your dataset:
- `head(n)` → first *n* rows (default 5)
- `tail(n)` → last *n* rows
- `info()` → columns, non-null counts, and dtypes
- `shape` → (rows, columns)
- `dtypes` → data type of each column

In [ ]:
'''Basic Inspection'''
#kisi bhi data type ko starting ke 5 and last ke 5 rows se samjha ja sakta hai
#In pandas "" ke andar jo bhi aaya wo object

In [ ]:
import pandas as pd

# Create a small DataFrame
a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "Score": [88, 92, 79, 85, 95]
}

b = pd.DataFrame(a)
print(b)


#1. If we want to see only starting ke rows(Default 5 hota hai)
b.head(2)

#2. If we want to look up from the bottomor from the end(Default 5 hota hai)
b.tail(2)

#3. if we want to see about the info of the dataframe
b.info()

#4. shape of the dataframe
b.shape

#5. To check type of column
b.dtypes

#6. To display statistical summary
b.describe()

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Score   5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

Name     object
Age       int64
Score     int64
dtype: object

## 2 Selecting Columns & Rows
Ways to access parts of a DataFrame:
- Single column → `df['col']`
- Multiple columns → `df[['col1','col2']]`
- Label-based selection → `df.loc[row_label, col_label]`
- Integer-index selection → `df.iloc[row_idx, col_idx]`
Tip: `:` means "all rows/columns" in that dimension.

In [ ]:
print(b)

#1. Selecting only one column (age vala)
print(b['Age'])

#2. Selecting multiple column -> list os list banana padta hai
print(b[['Age','Score']])

#3. Label based selection
b.loc[2,"Age"]  #output = 35 [row label, col label]
b.loc[4,"Score"]
b.loc[1,["Age","Score"]]
b.loc[1:3,["Name","Score"] ]   #Useful for filtering...  ->yha par end value bhi count hoti hai

#4. Integer index selection
#  .iloc() -> Index location
b.iloc[3]  #row index = 3 ka data mil jaayega
b.iloc[1:3]  #we will get data from Row index starting from 1 till 2  -> last value count nhi hogi
b.iloc[1:3,1:3]    #filtering

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95
0    25
1    30
2    35
3    40
4    22
Name: Age, dtype: int64
   Age  Score
0   25     88
1   30     92
2   35     79
3   40     85
4   22     95

   Age  Score
1   30     92
2   35     79

## 3 Index & Columns Overview
- `df.index` → row labels
- `df.columns` → column names
- `df.values` → underlying NumPy array (read-only; prefer using DataFrame ops)

In [ ]:
print(b)

b.index  #row ki start,stop,step
b.columns  #name of the columns
b.values  #Datafrome converts into matrix form

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

array([['Alice', 25, 88],
       ['Bob', 30, 92],
       ['Charlie', 35, 79],
       ['David', 40, 85],
       ['Emma', 22, 95]], dtype=object)

## 4 Renaming Columns & Setting an Index
- Rename columns → `df.rename(columns={'old':'new'}, inplace=False)`
- Set a column as index → `df.set_index('column_name', inplace=False)`
- Reset index → `df.reset_index(inplace=False)`
 If you don't use `inplace=True`, remember to assign the result back to a variable.

In [ ]:
print(b)

#1. Renaming the column
c = b.rename(columns={'Score':'Marks'})   #kisko karna hai:kisse karna hai
print(c)

#2. Changing the index
#(Index koi column hona chahiye jo already bana hua hai, woh sirf usse exchange ho sakta hai to pehele ek column create kar lenge)

c['Index'] = ['A','B','C','D','E']  #creating a new index
c.set_index('Index', inplace=True)  # inplace=True  -> ye original dataframe mein change kar dega
print(c)

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95
      Name  Age  Marks
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95
          Name  Age  Marks
Index
A        Alice   25     88
B          Bob   30     92
C      Charlie   35     79
D        David   40     85
E         Emma   22     95

## 5 Basic Attributes Recap
- `df.columns` → names of all columns
- `df.index` → row labels
- `df.values` → NumPy array (data only)
These are handy for quick checks and loops (though vectorized ops are preferred).

## Mini Practice
1. Create a DataFrame with at least 5 rows and 4 columns (mix of numeric + text).
2. Show the first 3 rows, last 2 rows, and the info.
3. Select a sub-DataFrame with only 2 columns.
4. Rename one column and set any column as index, then reset it back.
5. Print `df.shape`, `df.dtypes`, and `df.columns`.

In [ ]:
import pandas as pd

# Create a DataFrame with at least 5 rows & 4 columns (mix of numbers + text)
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "City": ["Delhi", "Mumbai", "Pune", "Bangalore", "Chennai"],
    "Score": [85, 91, 78, 88, 95]
}

df = pd.DataFrame(data)
print(df)

# Show the first 3 rows, last 2 rows, and info
df.head(3)
df.tail(2)
df.info()

# Select a sub-DataFrame with only 2 columns
df[['Age','City']]

# Rename one column and set any column as index, then reset it back
c = df.rename(columns = {'Name':'Title'})
print(c)

c.set_index('Score', inplace=True)
print(c)

c.reset_index(inplace = True)
print(c)


# Print df.shape, df.dtypes, and df.columns
print(df.shape)
print(df.dtypes)
print(df.columns)

      Name  Age       City  Score
0    Alice   25      Delhi     85
1      Bob   30     Mumbai     91
2  Charlie   35       Pune     78
3    David   40  Bangalore     88
4     Emma   22    Chennai     95
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   City    5 non-null      object
 3   Score   5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes
     Title  Age       City  Score
0    Alice   25      Delhi     85
1      Bob   30     Mumbai     91
2  Charlie   35       Pune     78
3    David   40  Bangalore     88
4     Emma   22    Chennai     95
         Title  Age       City
Score
85       Alice   25      Delhi
91         Bob   30     Mumbai
78     Charlie   35       Pune
88       David   40  Bangalore
95        Emma   22    Chennai
   Score    Title  Age       City
0     85    Alice   25      Delhi
1     91      Bob   30     Mumbai
2     78  Charlie   35       Pune
3     88    David   40  Bangalore
4     95     Emma   22    Chennai

---
## ✅ Summary
- You learned to **inspect** a DataFrame (`head`, `tail`, `info`, `shape`, `dtypes`).
- You practiced **selecting** columns/rows using `[]`, `.loc`, and `.iloc`.
- You explored **index/columns** and basic attributes.
- You **renamed** columns and **set/reset** an index.

Next up: **Data Cleaning Essentials** (missing values, types, duplicates).