<a href="https://colab.research.google.com/github/riddhimach24-dev/Data_Science/blob/main/02_Pandas/Pandas_day4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas - Class 4: Data Selection & Filtering
Welcome to **Class 4** of our Pandas series. Today we’ll explore techniques to select and filter data in a DataFrame.

In [ ]:
## CREATE MISSING VALUES
# using .loc() and assign value as np.nan
import pandas as pd

df = pd.DataFrame({
    "Name": ['Aman', 'Neha', 'Ravi', 'Priya', 'Karan', 'Simran'],
    "Age": [20, 21, 19, 22, 20, 21],
    "Score": [85, 92, 78, 88, 95, 90],
    "City": ['Delhi', 'Mumbai', 'Pune', 'Indore', 'Bhopal', 'Delhi'],
    "Height": [5.7, 5.4, 5.8, 5.5, 5.9, 5.6]
})
print(df)


#Creating a copy of a dataframe
df1 = df.copy()
df1

#making Neha's age and Ravi's marks as null
df1.loc[1, 'Age'] = None
df1.loc[2, 'Score'] = np.nan
print(df1)

     Name  Age  Score    City  Height
0    Aman   20     85   Delhi     5.7
1    Neha   21     92  Mumbai     5.4
2    Ravi   19     78    Pune     5.8
3   Priya   22     88  Indore     5.5
4   Karan   20     95  Bhopal     5.9
5  Simran   21     90   Delhi     5.6
     Name   Age  Score    City  Height
0    Aman  20.0   85.0   Delhi     5.7
1    Neha   NaN   92.0  Mumbai     5.4
2    Ravi  19.0    NaN    Pune     5.8
3   Priya  22.0   88.0  Indore     5.5
4   Karan  20.0   95.0  Bhopal     5.9
5  Simran  21.0   90.0   Delhi     5.6

## 1. Boolean Indexing & Conditional Selection
- Use comparison operators to build conditions (e.g., `df['col'] > 50`).
- Pass the condition inside `df[...]` to get matching rows.
- Combine multiple conditions with `&` (AND), `|` (OR), and `~` (NOT).
- Parentheses are required when combining conditions.

In [ ]:
import pandas as pd


a = pd.DataFrame({
    "Name" : ['Tanishq Patel', 'Atishay', 'Krishna', 'Raj', 'Agam'],
    "Age" : [21,39,23,42,25],
    "Score" : [70,65,60,80,90]
})
print(a)

#1. Single Condition: Rows where age>30

#a['Age'] > 30    #Boolean indexing aaygi (True/False)
a[a['Age'] > 30]
a[a['Score'] >= 80]


#2. Multiple Conditions: Age>=25 AND Score>80

a[(a['Age'] >= 25) & (a['Score'] > 80)]     #AND (&)
'''(condition1) operator(and/or/not) (conndition2)'''

a[(a['Age'] >= 25) | (a['Score'] > 80)]    #OR (|)

a[(a['Age'] >= 25) | (a['Score'] > 80)]    #NOT (~)

a[~(a['Score'] > 80)]

            Name  Age  Score
0  Tanishq Patel   21     70
1        Atishay   39     65
2        Krishna   23     60
3            Raj   42     80
4          Agam    25     90

            Name  Age  Score
0  Tanishq Patel   21     70
1        Atishay   39     65
2        Krishna   23     60
3            Raj   42     80

## 2. Filtering Rows with Multiple Conditions
- Combine two or more conditions to refine selection.
- Remember to enclose each condition in parentheses.

In [ ]:
#1. Age > 25 AND Score >= 85
#2. Age < 35 OR Score >= 80
#3. Age b/w 25 and 35 (inclusive.)

'''Solution 3'''
a[(a['Age'] >= 25) & (a['Age'] <=35)]

    Name  Age  Score
4  Agam    25     90

## 3. Using `query()` for Cleaner Filtering
- `query()` allows filtering rows with a string expression.
- It's concise and readable for complex conditions.
- Variables can be passed using the `@` symbol.

In [ ]:
#Simple query: Age>25
a.query("Age > 25")     #query mai boolean wali cheez nhi hoti

#Age < 35 and Score >= 85    #Query ke andr prompt simple english mai dena hai
a.query("Age<35 and Score>=85")

s = 80
a.query("Score > @s")    #@ ke baad variable aayga

    Name  Age  Score
4  Agam    25     90

## 4. String Operations on Columns
- Use the `.str` accessor for vectorized string methods.
- Common methods: `contains`, `replace`, `startswith`, `endswith`, `lower`, `upper`.
- Useful for cleaning or filtering text data.

In [ ]:
#1. Convert to LowerCase
a['Name'].str.lower()

#2. Convert to UpperCase
a['Name'].str.upper()

#3. Check if name contains the letter 'a'
a[a['Name'].str.contains('a')]

#4. Replace a substring to something else
a['Name'].str.replace('Agam','Agam Jain')

#5. Filter rows where name starts with 'D'
a[a['Name'].str.startswith('a')]

#6. Filter rows where name ends with 'e'
a[a['Name'].str.endswith('a')]

      Name  Age  Score
2  Krishna   23     60

## Mini Practice
1. Build a DataFrame with columns such as Name, Age, City, Score.
2. Use boolean indexing to select rows where Age > 25.
3. Filter rows where City is either 'Delhi' or 'Mumbai'.
4. Use query() to find rows with Score >= 85 and Age < 35.
5. Clean a text column using str.replace or str.lower.

In [ ]:


# 1. Build a DataFrame with columns: Name, Age, City, Score
import pandas as pd
import numpy as np

data = {
    "Name": ["Aman","Neha","Ravi","Priya","Karan","Neha","Rohit","Simran"],
    "Age": [20,21,26,22,20,31,23,34],
    "City": ["Delhi","Mumbai","Pune","Indore","Delhi","Mumbai","Pune","Delhi"],
    "Score": [85,92,78,np.nan,95,92,88,90],
}

df = pd.DataFrame(data)
df

# 2. Use boolean indexing to select rows where Age > 25
df[df['Age'] > 25]

# 3. Filter rows where City is either 'Delhi' or 'Mumbai'
df[(df['City'] == 'Delhi') | (df['City'] == 'Mumbai')]


# 4. Use query() to find rows with Score >= 85 and Age < 35
df.query(" Score >= 85 and Age < 35")

# 5. Clean a text column using str.replace or str.lower
# Example: convert City names to lowercase or replace "delhi" with "New Delhi"
df['City'].str.lower()
df['City'].str.replace('Delhi', 'NewDelhi')
df

     Name  Age    City  Score
0    Aman   20   Delhi   85.0
1    Neha   21  Mumbai   92.0
2    Ravi   26    Pune   78.0
3   Priya   22  Indore    NaN
4   Karan   20   Delhi   95.0
5    Neha   31  Mumbai   92.0
6   Rohit   23    Pune   88.0
7  Simran   34   Delhi   90.0

---
## Summary
- Learned to use boolean indexing and conditional selection.
- Filtered rows with multiple conditions.
- Used `query()` for clean filtering.
- Applied string operations with the `.str` accessor.