<a href="https://colab.research.google.com/github/riddhimach24-dev/Data_Science/blob/main/02_Pandas/Pandas_day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas - Class 1: Introduction & Setup
Welcome to your first class on **Pandas**. In this session, we'll learn what Pandas is, why we use it, and how to get started with Series and DataFrames.

## 1 What is Pandas and Why Use It?
Pandas is a powerful **Python library** for data analysis and manipulation.

Key points:
- Provides two main data structures: **Series** (1D) and **DataFrame** (2D).
- Makes working with tabular data easy and fast.
- Ideal for cleaning, transforming, and analyzing datasets.
- Works well with other libraries like NumPy, Matplotlib, and Scikit-Learn.

## 2 Installing & Importing Pandas
To install pandas, open your terminal or command prompt and run:
```bash
pip install pandas
```
Then, you can import it in Python as follows:

In [ ]:
import pandas as pd

## 3 Understanding Series & DataFrame
- **Series**: One-dimensional labeled array, like a column in Excel.
- **DataFrame**: Two-dimensional table, similar to an Excel sheet or SQL table.

### Creating a Series from Python Lists or Dictionaries

In [ ]:
a = [10,20,30,40,50]  #LISTS
pd.Series(a)   #This is series (only a single column)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
a = [10,20,30,40,50]
b = pd.Series(a, name = "Marks")
print(b) #to change column name

0    10
1    20
2    30
3    40
4    50
Name: Marks, dtype: int64

In [ ]:
c = {'Devraj':90, 'Agam':80, 'Riddhi':95, 'Krishu':85}    #DICTIONARY
pd.Series(c, name = "Marks")

Devraj    90
Agam      80
Riddhi    95
Krishu    85
Name: Marks, dtype: int64

### Creating a DataFrame

In [ ]:
#Dataframe - multiple columns (only created using dictionary)

#whenever we create dataframe we need two things
#1. Column name: uspe aane waali values
d = {
    'Name':['Agam', 'Devraj', 'Bindu', 'Hariom'],
    'Marks':[70, 24, 90, 85],
    'Subject':['Maths', 'Science', 'English', 'Hindi']

}

df = pd.DataFrame(d)
print(df)

     Name  Marks  Subject
0    Agam     70    Maths
1  Devraj     24  Science
2   Bindu     90  English
3  Hariom     85    Hindi

### Creating DataFrame from NumPy Arrays

In [ ]:
import numpy as np
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

pd.DataFrame(arr, columns = ['A', 'B', 'C'])

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

### Reading CSV / Excel Files (Sneak Peek)
You can read external data using:
```python
pd.read_csv('file.csv')
```
```python
pd.read_excel('file.xlsx')
```
We will explore this in detail later.

---
**Summary**
- Pandas is a must-know library for data analysis.
- We learned about Series & DataFrames.
- We saw how to create them from lists, dictionaries, NumPy arrays, and got a sneak peek at CSV/Excel files.