<a href="https://colab.research.google.com/github/riddhimach24-dev/Data_Science/blob/main/02_Pandas/Assignments/sheet2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Assignment (Q1–Q15)

Fill the code in the empty code cells.

In [2]:
import pandas as pd
import numpy as np

## Q1. Create the above DataFrame.

Expected Output:
```
    Name   Age  Marks     City
0   Aman  20.0   85.0    Delhi
1   Neha   NaN   92.0   Mumbai
2   Ravi  19.0    NaN     Pune
3  Priya  22.0   88.0  Indore
4  Karan  20.0   95.0      NaN
```

In [3]:
a = {
    "Name": ['Aman', 'Neha', 'Ravi', 'Priya', 'Karan'],
    "Age": [20, None, 19, 22, 20],
    "Marks": [85, 92, None, 88, 95],
    "City": ['Delhi', 'Mumbai', 'Pune', 'Indore', None]

}
df = pd.DataFrame(a)
print(df)

    Name   Age  Marks    City
0   Aman  20.0   85.0   Delhi
1   Neha   NaN   92.0  Mumbai
2   Ravi  19.0    NaN    Pune
3  Priya  22.0   88.0  Indore
4  Karan  20.0   95.0    None

## Q2. Display the first 3 rows.

In [4]:
df.head(3)

   Name   Age  Marks    City
0  Aman  20.0   85.0   Delhi
1  Neha   NaN   92.0  Mumbai
2  Ravi  19.0    NaN    Pune

## Q3. Display the last 2 rows.

In [5]:
df.tail(2)

    Name   Age  Marks    City
3  Priya  22.0   88.0  Indore
4  Karan  20.0   95.0    None

## Q4. Find the shape of the DataFrame.

In [6]:
df.shape

(5, 4)

## Q5. Display all column names.

In [21]:
df.columns

Index(['Name', 'Age', 'Marks', 'City'], dtype='object')

## Q6. Display the data types of all columns.

In [8]:
df.dtypes

Name      object
Age      float64
Marks    float64
City      object
dtype: object

## Q7. Find the total number of missing values in each column using `isnull().sum()`.

Expected Output:
```
Name     0
Age      1
Marks    1
City     1
dtype: int64
```

In [9]:
df.isnull().sum()

Name     0
Age      1
Marks    1
City     1
dtype: int64

## Q8. Fill missing values in the Age column with **21** using `fillna()`.

In [10]:
df['Age'] = df['Age'].fillna(21)
print(df)

    Name   Age  Marks    City
0   Aman  20.0   85.0   Delhi
1   Neha  21.0   92.0  Mumbai
2   Ravi  19.0    NaN    Pune
3  Priya  22.0   88.0  Indore
4  Karan  20.0   95.0    None

## Q9. Fill missing values in the Marks column with the column mean.

In [12]:
df['Marks'] = df['Marks'].fillna(df['Marks'].mean())
print(df)

    Name   Age  Marks    City
0   Aman  20.0   85.0   Delhi
1   Neha  21.0   92.0  Mumbai
2   Ravi  19.0   90.0    Pune
3  Priya  22.0   88.0  Indore
4  Karan  20.0   95.0    None

## Q10. Fill missing values in the City column with **Unknown**.

In [13]:
df['City'] = df['City'].fillna('Unknown')
print(df)

    Name   Age  Marks     City
0   Aman  20.0   85.0    Delhi
1   Neha  21.0   92.0   Mumbai
2   Ravi  19.0   90.0     Pune
3  Priya  22.0   88.0   Indore
4  Karan  20.0   95.0  Unknown

## Q11. Select only the Name and Marks columns.

In [14]:
print(df[['Name', 'Marks']])

    Name  Marks
0   Aman   85.0
1   Neha   92.0
2   Ravi   90.0
3  Priya   88.0
4  Karan   95.0

## Q12. Using `loc`, print the first 3 rows.

In [16]:
df.loc[0:2]

   Name   Age  Marks    City
0  Aman  20.0   85.0   Delhi
1  Neha  21.0   92.0  Mumbai
2  Ravi  19.0   90.0    Pune

## Q13. Using `iloc`, print rows 1 to 3 and columns 0 to 2.

In [19]:
df.iloc[1:4, 0:3]

    Name   Age  Marks
1   Neha  21.0   92.0
2   Ravi  19.0   90.0
3  Priya  22.0   88.0

## Q14. Rename the column Marks to Score.

In [20]:
df1 = df.rename(columns={'Marks':'Score'})
print(df1)

    Name   Age  Score     City
0   Aman  20.0   85.0    Delhi
1   Neha  21.0   92.0   Mumbai
2   Ravi  19.0   90.0     Pune
3  Priya  22.0   88.0   Indore
4  Karan  20.0   95.0  Unknown

## Q15. Set Name as the index.

In [22]:
df1.set_index('Name', inplace= True)
print(df1)

        Age  Score     City
Name
Aman   20.0   85.0    Delhi
Neha   21.0   92.0   Mumbai
Ravi   19.0   90.0     Pune
Priya  22.0   88.0   Indore
Karan  20.0   95.0  Unknown