<a href="https://colab.research.google.com/github/riddhimach24-dev/Data_Science/blob/main/02_Pandas/Assignments/sheet4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Final Pandas Assignment — Classes 1 to 5

### Level: Beginner → Intermediate

Covers Classes 1–4 plus **only the first 2 topics of Class 5**:
- DataFrame & Series
- Indexing, Selection, `loc`, `iloc`
- DataFrame attributes
- Missing values: `isnull()`, `fillna()`, `dropna()`
- `rename()`, `set_index()`
- Sorting: `sort_values()`, `sort_index()`
- Statistics: `mean()`, `median()`, `mode()`, `std()`, `describe()`

**Instructions:** Do not load a CSV. Create the DataFrame in Q1 and use it for the remaining questions. Write your solution in each blank code cell.

## Q1. Create the DataFrame

Create a DataFrame with:

| Name | Age | Score | City | Height |
|---|---:|---:|---|---:|
| Aman | 20 | 85 | Delhi | 5.7 |
| Neha | 21 | 92 | Mumbai | 5.4 |
| Ravi | 19 | 78 | Pune | 5.8 |
| Priya | 22 | 88 | Indore | 5.5 |
| Karan | 20 | 95 | Bhopal | 5.9 |
| Simran | 21 | 90 | Delhi | 5.6 |

**Expected Output:** 6 rows × 5 columns.

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Name": ['Aman', 'Neha', 'Ravi', 'Priya', 'Karan', 'Simran'],
    "Age": [20, 21, 19, 22, 20, 21],
    "Score": [85, 92, 78, 88, 95, 90],
    "City": ['Delhi', 'Mumbai', 'Pune', 'Indore', 'Bhopal', 'Delhi'],
    "Height": [5.7, 5.4, 5.8, 5.5, 5.9, 5.6]
})
print(df)

     Name  Age  Score    City  Height
0    Aman   20     85   Delhi     5.7
1    Neha   21     92  Mumbai     5.4
2    Ravi   19     78    Pune     5.8
3   Priya   22     88  Indore     5.5
4   Karan   20     95  Bhopal     5.9
5  Simran   21     90   Delhi     5.6

## Q2. First 3 rows

Use `head(3)`. **Expected Output:** Aman, Neha, Ravi.

In [ ]:
df.head(3)

   Name  Age  Score    City  Height
0  Aman   20     85   Delhi     5.7
1  Neha   21     92  Mumbai     5.4
2  Ravi   19     78    Pune     5.8

## Q3. Last 2 rows

Use `tail(2)`. **Expected Output:** Karan and Simran.

In [ ]:
df.tail(2)

     Name  Age  Score    City  Height
4   Karan   20     95  Bhopal     5.9
5  Simran   21     90   Delhi     5.6

## Q4. DataFrame information

Use `info()`. **Expected Output:** Information about 6 rows and 5 columns.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      object
 1   Age     6 non-null      int64
 2   Score   6 non-null      int64
 3   City    6 non-null      object
 4   Height  6 non-null      float64
dtypes: float64(1), int64(2), object(2)
memory usage: 372.0+ bytes

## Q5. DataFrame attributes

Print `shape`, `columns`, and `index`. **Expected Output:** Shape is `(6, 5)`.

In [ ]:
print(df.shape)
print(df.columns)
print(df.index)

(6, 5)
Index(['Name', 'Age', 'Score', 'City', 'Height'], dtype='object')
RangeIndex(start=0, stop=6, step=1)

## Q6. Select one column

Select only `Name`. **Expected Output:** All six student names.

In [ ]:
df['Name']

0      Aman
1      Neha
2      Ravi
3     Priya
4     Karan
5    Simran
Name: Name, dtype: object

## Q7. Select multiple columns

Select `Name`, `Score`, and `City`. **Expected Output:** A 6×3 DataFrame.

In [ ]:
df[['Name', 'Score', 'City']]

     Name  Score    City
0    Aman     85   Delhi
1    Neha     92  Mumbai
2    Ravi     78    Pune
3   Priya     88  Indore
4   Karan     95  Bhopal
5  Simran     90   Delhi

## Q8. Use loc

Using `loc`, display rows for Neha, Ravi, and Priya. **Expected Output:** Rows with indexes 1, 2, 3.

In [ ]:
df.loc[1:3]

    Name  Age  Score    City  Height
1   Neha   21     92  Mumbai     5.4
2   Ravi   19     78    Pune     5.8
3  Priya   22     88  Indore     5.5

## Q9. Use iloc

Using `iloc`, display rows 2 to 4 and columns Name and Score. **Expected Output:** Ravi, Priya, Karan with scores.

In [ ]:
df.loc[2:4, ['Name', 'Score']]

    Name  Score
2   Ravi     78
3  Priya     88
4  Karan     95

## Q10. Conditional selection

Display students whose Score is greater than 85. **Expected Output:** Neha, Priya, Karan, Simran.

In [ ]:
df[df['Score'] > 85]

     Name  Age  Score    City  Height
1    Neha   21     92  Mumbai     5.4
3   Priya   22     88  Indore     5.5
4   Karan   20     95  Bhopal     5.9
5  Simran   21     90   Delhi     5.6

## Q11. Add a column

Create `Passed` as True when Score >= 40. **Expected Output:** True for all students.

In [ ]:
df['Passed'] = df['Score'] >= 40
df

     Name  Age  Score    City  Height  Passed
0    Aman   20     85   Delhi     5.7    True
1    Neha   21     92  Mumbai     5.4    True
2    Ravi   19     78    Pune     5.8    True
3   Priya   22     88  Indore     5.5    True
4   Karan   20     95  Bhopal     5.9    True
5  Simran   21     90   Delhi     5.6    True

## Q12. Rename a column

Rename `Score` to `Marks`. **Expected Output:** `Marks` replaces `Score`.

In [ ]:
df.rename(columns= {'Marks': 'Score'})

     Name  Age  Score    City  Height  Passed
0    Aman   20     85   Delhi     5.7    True
1    Neha   21     92  Mumbai     5.4    True
2    Ravi   19     78    Pune     5.8    True
3   Priya   22     88  Indore     5.5    True
4   Karan   20     95  Bhopal     5.9    True
5  Simran   21     90   Delhi     5.6    True

## Q13. Set index

Set `Name` as the index. **Expected Output:** Names become row labels.

In [ ]:
df.set_index('Name')

        Age  Score    City  Height  Passed
Name
Aman     20     85   Delhi     5.7    True
Neha     21     92  Mumbai     5.4    True
Ravi     19     78    Pune     5.8    True
Priya    22     88  Indore     5.5    True
Karan    20     95  Bhopal     5.9    True
Simran   21     90   Delhi     5.6    True

## Q14. Create missing values

Create a copy and make Neha's Age and Ravi's Marks `np.nan`. **Expected Output:** One missing Age and one missing Marks.

In [ ]:
import numpy as np
df_copy = df.copy()
df_copy.loc[1, 'Age'] = np.nan
df_copy.loc[2, 'Score'] = np.nan
print(df_copy)

     Name   Age  Score    City  Height  Passed
0    Aman  20.0   85.0   Delhi     5.7    True
1    Neha   NaN   92.0  Mumbai     5.4    True
2    Ravi  19.0    NaN    Pune     5.8    True
3   Priya  22.0   88.0  Indore     5.5    True
4   Karan  20.0   95.0  Bhopal     5.9    True
5  Simran  21.0   90.0   Delhi     5.6    True

## Q15. Find missing values

Use `isnull().sum()`. **Expected Output:** Age = 1, Marks = 1, others = 0.

In [ ]:
df_copy.isnull().sum()

Name      0
Age       1
Score     1
City      0
Height    0
Passed    0
dtype: int64

## Q16. Fill missing Age

Fill missing Age with 21 using `fillna()`. **Expected Output:** Neha's Age becomes 21.

In [ ]:
df_copy['Age'] = df_copy['Age'].fillna(21)
print(df_copy)

     Name   Age  Score    City  Height  Passed
0    Aman  20.0   85.0   Delhi     5.7    True
1    Neha  21.0   92.0  Mumbai     5.4    True
2    Ravi  19.0    NaN    Pune     5.8    True
3   Priya  22.0   88.0  Indore     5.5    True
4   Karan  20.0   95.0  Bhopal     5.9    True
5  Simran  21.0   90.0   Delhi     5.6    True

## Q17. Fill missing Marks

Fill missing Marks with the Marks-column mean. **Expected Output:** Ravi's missing Marks is replaced by the mean.

In [ ]:
df_copy['Score'] = df_copy['Score'].fillna(df_copy['Score'].mean())

print(df_copy)

     Name   Age  Score    City  Height  Passed
0    Aman  20.0   85.0   Delhi     5.7    True
1    Neha  21.0   92.0  Mumbai     5.4    True
2    Ravi  19.0   90.0    Pune     5.8    True
3   Priya  22.0   88.0  Indore     5.5    True
4   Karan  20.0   95.0  Bhopal     5.9    True
5  Simran  21.0   90.0   Delhi     5.6    True

## Q18. Sort by Marks

Sort Marks in descending order using `sort_values()`. **Expected Output:** Highest Marks first.

In [ ]:
df_copy.sort_values(by= 'Score', ascending= False)

     Name   Age  Score    City  Height  Passed
4   Karan  20.0   95.0  Bhopal     5.9    True
1    Neha  21.0   92.0  Mumbai     5.4    True
5  Simran  21.0   90.0   Delhi     5.6    True
2    Ravi  19.0   90.0    Pune     5.8    True
3   Priya  22.0   88.0  Indore     5.5    True
0    Aman  20.0   85.0   Delhi     5.7    True

## Q19. Sort by multiple columns

Sort by City ascending and Marks descending. **Expected Output:** Cities alphabetical; higher Marks first within a City.

In [ ]:
df_copy.sort_values(by= ['City', 'Score'], ascending= [True, False])

     Name   Age  Score    City  Height  Passed
4   Karan  20.0   95.0  Bhopal     5.9    True
5  Simran  21.0   90.0   Delhi     5.6    True
0    Aman  20.0   85.0   Delhi     5.7    True
3   Priya  22.0   88.0  Indore     5.5    True
1    Neha  21.0   92.0  Mumbai     5.4    True
2    Ravi  19.0   90.0    Pune     5.8    True

## Q20. Sort by index

After setting Name as index, use `sort_index()`. **Expected Output:** Names alphabetical.

In [ ]:
df_copy.set_index('Name').sort_index()

         Age  Score    City  Height  Passed
Name
Aman    20.0   85.0   Delhi     5.7    True
Karan   20.0   95.0  Bhopal     5.9    True
Neha    21.0   92.0  Mumbai     5.4    True
Priya   22.0   88.0  Indore     5.5    True
Ravi    19.0   90.0    Pune     5.8    True
Simran  21.0   90.0   Delhi     5.6    True

## Q21. Basic statistics

Calculate `mean()`, `median()`, `mode()`, and `std()` for Marks. **Expected Output:** Four statistical results.

In [ ]:
print(df_copy['Score'].mean())
print(df_copy['Score'].median())
print(df_copy['Score'].mode())
print(df_copy['Score'].std())

90.0
90.0
0    90.0
Name: Score, dtype: float64
3.40587727318528

## Q22. Descriptive statistics

Use `describe()` on numeric columns. **Expected Output:** count, mean, std, min, quartiles, and max.

In [ ]:
df_copy.describe()

             Age      Score    Height
count   6.000000   6.000000  6.000000
mean   20.500000  90.000000  5.650000
std     1.048809   3.405877  0.187083
min    19.000000  85.000000  5.400000
25%    20.000000  88.500000  5.525000
50%    20.500000  90.000000  5.650000
75%    21.000000  91.500000  5.775000
max    22.000000  95.000000  5.900000

# ⭐ Final Challenge

Using the DataFrame:
1. Handle missing values.
2. Sort by Marks from highest to lowest.
3. Show students with Marks above 85.
4. Calculate average Marks.
5. Display the final cleaned DataFrame.

**Expected Result:** A clean, sorted and filtered DataFrame plus the average Marks.

In [ ]:
#print(df_copy)

df_copy  = df_copy.sort_values(by= 'Score', ascending= False)
df_copy = df_copy[df_copy['Score'] > 85]


print("Final cleaned DataFrame:")
print(df_copy)
print("Average Marks:",df_copy['Score'].mean())

Final cleaned DataFrame:
     Name   Age  Score    City  Height  Passed
4   Karan  20.0   95.0  Bhopal     5.9    True
1    Neha  21.0   92.0  Mumbai     5.4    True
5  Simran  21.0   90.0   Delhi     5.6    True
2    Ravi  19.0   90.0    Pune     5.8    True
3   Priya  22.0   88.0  Indore     5.5    True
Average Marks: 91.0