<a href="https://colab.research.google.com/github/riddhimach24-dev/Data_Science/blob/main/02_Pandas/Assignments/sheet5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Final Pandas Assignment — Classes 1 to 6

### Level: Beginner → Intermediate → Practical

This assignment revises Classes 1–4 and gives **extra focus to Class 5 (Sorting & Basic Statistics)** and **Class 6 (GroupBy & Aggregations)**.

### Instructions
- Do **not** load a CSV file.
- When Class 6 starts, create the **8-column DataFrame in Q21**.
- Use that same DataFrame for the remaining Class 5 + Class 6 practice.
- Every question has an **Expected Output / I-O hint**.
- Write your solution in the blank code cell below each question.

### Class 6 Main Skills
`groupby()` • `agg()` • `pivot_table()` • `crosstab()`

# Part A — Pandas Basics & DataFrame Creation

### Q1. Import Pandas using the alias `pd`.

**Expected Output: Pandas is imported successfully.**

In [ ]:
import pandas as pd

### Q2. Create a Series containing: `10, 20, 30, 40, 50`.

**Expected Output: A Series with 5 values.**

In [ ]:
a = [10,20,30,40,50]
pd.Series(a)

0    10
1    20
2    30
3    40
4    50
dtype: int64

### Q3. Create a small DataFrame with columns `Name`, `Age`, and `City` using a dictionary.

**Expected Output: A DataFrame with at least 5 rows.**

In [ ]:
a = pd.DataFrame({
    'Name': ['Kiran', 'Mahesh', 'Sobhit', 'Aarav', 'Dakshita'],
    'Age': [18, 20, 29, 22, 19],
    'City': ['Delhi', 'Mumbai', 'Pune', 'Banglore', 'Hyderabad']
})

print(a)

       Name  Age       City
0     Kiran   18      Delhi
1    Mahesh   20     Mumbai
2    Sobhit   29       Pune
3     Aarav   22   Banglore
4  Dakshita   19  Hyderabad

### Q4. Display the first 3 rows using `head(3)`.

**Expected Output: First 3 rows are displayed.**

In [ ]:
a.head(3)

     Name  Age    City
0   Kiran   18   Delhi
1  Mahesh   20  Mumbai
2  Sobhit   29    Pune

### Q5. Display the last 2 rows using `tail(2)`.

**Expected Output: Last 2 rows are displayed.**

In [ ]:
a.tail(2)

       Name  Age       City
3     Aarav   22   Banglore
4  Dakshita   19  Hyderabad

### Q6. Print the DataFrame `shape`, `columns`, and `index`.

**Expected Output: Shape, column names, and row index are displayed.**

In [ ]:
print(a.shape)
print(a.columns)
print(a.index)

(5, 3)
Index(['Name', 'Age', 'City'], dtype='object')
RangeIndex(start=0, stop=5, step=1)

### Q7. Select one column and then select two columns together.

**Expected Output: A Series for one column and a DataFrame for two columns.**

In [ ]:
print(a['Name'])
print(a[['City', 'Age']])

0       Kiran
1      Mahesh
2      Sobhit
3       Aarav
4    Dakshita
Name: Name, dtype: object
        City  Age
0      Delhi   18
1     Mumbai   20
2       Pune   29
3   Banglore   22
4  Hyderabad   19

### Q8. Use `loc` to select the first 3 rows.

**Expected Output: First 3 rows are displayed.**

In [ ]:
a.loc[0:2]

     Name  Age    City
0   Kiran   18   Delhi
1  Mahesh   20  Mumbai
2  Sobhit   29    Pune

### Q9. Use `iloc` to select rows 1–3 and the first 2 columns.

**Expected Output: Required rows and columns are displayed.**

In [ ]:
a.iloc[1:4, 0:2]

     Name  Age
1  Mahesh   20
2  Sobhit   29
3   Aarav   22

### Q10. Rename one column using `rename()`.

**Expected Output: The selected column name is changed.**

In [ ]:
a.rename(columns={'City':'UrbanCenter'})

       Name  Age UrbanCenter
0     Kiran   18       Delhi
1    Mahesh   20      Mumbai
2    Sobhit   29        Pune
3     Aarav   22    Banglore
4  Dakshita   19   Hyderabad

### Q11. Find missing values using `isnull().sum()`.

**Expected Output: Missing-value count for every column.**

In [ ]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, np.nan, 30, 22],
    'Score': [85.0, 92.0, None, 78.0]
}

df = pd.DataFrame(data)
print(df)

df.isnull().sum()

      Name   Age  Score
0    Alice  25.0   85.0
1      Bob   NaN   92.0
2  Charlie  30.0    NaN
3    David  22.0   78.0

Name     0
Age      1
Score    1
dtype: int64

### Q12. Use `fillna()` to replace a missing value in a numeric column.

**Expected Output: The missing value is filled.**

In [ ]:
df['Score'].fillna(df['Score'].mean())

0    85.0
1    92.0
2    85.0
3    78.0
Name: Score, dtype: float64

# Part B — Sorting & Basic Statistics (Class 5 Focus)

### Q13. Sort a numeric column in ascending order using `sort_values()`.

**Expected Output: Smallest value appears first.**

In [ ]:
print(a)

a.sort_values(by= 'Age', ascending= True)

       Name  Age       City
0     Kiran   18      Delhi
1    Mahesh   20     Mumbai
2    Sobhit   29       Pune
3     Aarav   22   Banglore
4  Dakshita   19  Hyderabad

       Name  Age       City
0     Kiran   18      Delhi
4  Dakshita   19  Hyderabad
1    Mahesh   20     Mumbai
3     Aarav   22   Banglore
2    Sobhit   29       Pune

### Q14. Sort the same column in descending order.

**Expected Output: Largest value appears first.**

In [ ]:
a.sort_values(by= 'Age', ascending= False)

       Name  Age       City
2    Sobhit   29       Pune
3     Aarav   22   Banglore
1    Mahesh   20     Mumbai
4  Dakshita   19  Hyderabad
0     Kiran   18      Delhi

### Q15. Sort by two columns: first by a categorical column and then by a numeric column.

**Expected Output: Data is grouped by the first column and sorted by the second within each group.**

In [ ]:
a.sort_values(by= ['City', 'Age'])

       Name  Age       City
3     Aarav   22   Banglore
0     Kiran   18      Delhi
4  Dakshita   19  Hyderabad
1    Mahesh   20     Mumbai
2    Sobhit   29       Pune

### Q16. Use `sort_index()` to sort rows by their index.

**Expected Output: Index is in ascending order.**

In [ ]:
a.sort_index()

       Name  Age       City
0     Kiran   18      Delhi
1    Mahesh   20     Mumbai
2    Sobhit   29       Pune
3     Aarav   22   Banglore
4  Dakshita   19  Hyderabad

### Q17. Calculate the mean of a numeric column.

**Expected Output: One mean value.**

In [ ]:
a.mean(numeric_only= True)

Age    21.6
dtype: float64

### Q18. Calculate the median and mode of a numeric column.

**Expected Output: Median and mode are displayed.**

In [ ]:
print(a.median(numeric_only= True))
print(a.mode(numeric_only= True))

Age    20.0
dtype: float64
   Age
0   18
1   19
2   20
3   22
4   29

### Q19. Calculate the standard deviation using `std()`.

**Expected Output: One standard-deviation value.**

In [ ]:
a.std(numeric_only= True)

Age    4.393177
dtype: float64

### Q20. Use `describe()` on the numeric columns.

**Expected Output: count, mean, std, min, quartiles, and max are displayed.**

In [ ]:
a.describe()

             Age
count   5.000000
mean   21.600000
std     4.393177
min    18.000000
25%    19.000000
50%    20.000000
75%    22.000000
max    29.000000

# Part C — Create the Main 8-Column DataFrame (Class 6 Starts Here)

### Q21. Create this DataFrame with **8 columns**:

| Department | Employee | Salary | Age | City | Experience | Score | Gender |
|---|---|---:|---:|---|---:|---:|---|
| IT | Aman | 55000 | 24 | Delhi | 2 | 82 | M |
| HR | Neha | 48000 | 27 | Mumbai | 4 | 88 | F |
| IT | Ravi | 62000 | 29 | Pune | 5 | 91 | M |
| Sales | Priya | 45000 | 25 | Delhi | 3 | 76 | F |
| IT | Karan | 70000 | 32 | Bhopal | 8 | 95 | M |
| HR | Simran | 52000 | 30 | Delhi | 6 | 89 | F |
| Sales | Arjun | 50000 | 28 | Mumbai | 5 | 84 | M |
| IT | Pooja | 58000 | 26 | Pune | 3 | 87 | F |
| HR | Mohit | 46000 | 23 | Bhopal | 1 | 73 | M |
| Sales | Anjali | 54000 | 31 | Delhi | 7 | 92 | F |
| IT | Rahul | 65000 | 35 | Mumbai | 10 | 90 | M |
| HR | Isha | 50000 | 26 | Pune | 3 | 85 | F |

**Expected Output:** DataFrame with **12 rows and 8 columns**.

In [ ]:
A = pd.DataFrame({
    'Department': ['IT', 'HR', 'IT', 'Sales', 'IT', 'HR', 'Sales', 'IT', 'HR', 'Sales', 'IT', 'HR'],
    'Employee': ['Aman', 'Neha', 'Ravi', 'Priya', 'Karan', 'Simran', 'Arjun', 'Pooja', 'Mohit', 'Anjali', 'Rahul', 'Isha'],
    'Salary': [55000, 48000, 62000, 45000, 70000, 52000, 50000, 58000, 46000, 54000, 65000, 50000],
    'Age': [24, 27, 29, 25, 32, 30, 28, 26, 23, 31, 35, 26],
    'City': ['Delhi', 'Mumbai', 'Pune', 'Delhi', 'Bhopal', 'Delhi', 'Mumbai', 'Pune', 'Bhopal', 'Delhi', 'Mumbai', 'Pune'],
    'Experience': [2, 4, 5, 3, 8, 6, 5, 3, 1, 7, 10, 3],
    'Score': [82, 88, 91, 76, 95, 89, 84, 87, 73, 92, 90, 85],
    'Gender': ['M', 'F', 'M', 'F', 'M', 'F', 'M', 'F', 'M', 'F', 'M', 'F']

})

print(A)

   Department Employee  Salary  Age    City  Experience  Score Gender
0          IT     Aman   55000   24   Delhi           2     82      M
1          HR     Neha   48000   27  Mumbai           4     88      F
2          IT     Ravi   62000   29    Pune           5     91      M
3       Sales    Priya   45000   25   Delhi           3     76      F
4          IT    Karan   70000   32  Bhopal           8     95      M
5          HR   Simran   52000   30   Delhi           6     89      F
6       Sales    Arjun   50000   28  Mumbai           5     84      M
7          IT    Pooja   58000   26    Pune           3     87      F
8          HR    Mohit   46000   23  Bhopal           1     73      M
9       Sales   Anjali   54000   31   Delhi           7     92      F
10         IT    Rahul   65000   35  Mumbai          10     90      M
11         HR     Isha   50000   26    Pune           3     85      F

### Q22. Display the first 5 rows of this DataFrame.

**Expected Output: Aman through Karan.**

In [ ]:
A.head(5)

  Department Employee  Salary  Age    City  Experience  Score Gender
0         IT     Aman   55000   24   Delhi           2     82      M
1         HR     Neha   48000   27  Mumbai           4     88      F
2         IT     Ravi   62000   29    Pune           5     91      M
3      Sales    Priya   45000   25   Delhi           3     76      F
4         IT    Karan   70000   32  Bhopal           8     95      M

### Q23. Check the shape, columns, and data types.

**Expected Output: Shape is `(12, 8)`.**

In [ ]:
print(A.shape)
print(A.columns)
print(A.dtypes)

(12, 8)
Index(['Department', 'Employee', 'Salary', 'Age', 'City', 'Experience',
       'Score', 'Gender'],
      dtype='object')
Department    object
Employee      object
Salary         int64
Age            int64
City          object
Experience     int64
Score          int64
Gender        object
dtype: object

# Part D — GroupBy & Aggregations (Main Focus)

### Q24. Group by `Department` and calculate the **average Salary**.

**Expected Output: One average Salary value for IT, HR, and Sales.**

In [ ]:
avg_salary = A.groupby('Department')['Salary'].mean()
print(avg_salary)

Department
HR       49000.000000
IT       62000.000000
Sales    49666.666667
Name: Salary, dtype: float64

### Q25. Group by `Department` and calculate the **maximum Salary**.

**Expected Output: Maximum Salary for each department.**

In [ ]:
Max_salary = A.groupby('Department')['Salary'].max()
print(Max_salary)

Department
HR       52000
IT       70000
Sales    54000
Name: Salary, dtype: int64

### Q26. Group by `Department` and calculate the **minimum Age**.

**Expected Output: Minimum Age for each department.**

In [ ]:
Min_age = A.groupby('Department')['Age'].min()
print(Min_age)

Department
HR       23
IT       24
Sales    25
Name: Age, dtype: int64

### Q27. Group by `Department` and calculate the **number of employees**.

**Expected Output: IT = 5, HR = 4, Sales = 3.**

In [ ]:
Employee_count = A.groupby('Department')['Employee'].count()
print(Employee_count)

Department
HR       4
IT       5
Sales    3
Name: Employee, dtype: int64

### Q28. Group by `City` and calculate the average `Score`.

**Expected Output: One average Score for each city.**

In [ ]:
avg_score = A.groupby('City')['Score'].mean()
print(avg_score)

City
Bhopal    84.000000
Delhi     84.750000
Mumbai    87.333333
Pune      87.666667
Name: Score, dtype: float64

### Q29. Group by `Gender` and calculate the average `Salary`.

**Expected Output: Average Salary for M and F.**

In [ ]:
avg_salary = A.groupby('Gender')['Salary'].mean()
print(avg_salary)

Gender
F    51166.666667
M    58000.000000
Name: Salary, dtype: float64

### Q30. Use `groupby()` with `agg()` to find **mean Salary, maximum Age, and mean Score** for each Department.

**Expected Output: One row per department with 3 aggregated results.**

In [ ]:
multi_stats1 = A.groupby('Department').agg({
    'Salary': 'mean',
    'Age': 'max',
    'Score': 'mean'
})

print(multi_stats1)

                  Salary  Age  Score
Department
HR          49000.000000   30  83.75
IT          62000.000000   35  89.00
Sales       49666.666667   31  84.00

### Q31. Use `agg()` to calculate **mean Salary and maximum Experience** for each Department.

**Expected Output: Department-wise mean Salary and max Experience.**

In [ ]:
multi_stats2 = A.groupby('Department').agg({
    'Salary': 'mean',
    'Experience': 'max',
})

print(multi_stats2)

                  Salary  Experience
Department
HR          49000.000000           6
IT          62000.000000          10
Sales       49666.666667           7

### Q32. Find the department with the **highest average Salary**.

**Expected Output: One department name.**

In [ ]:
highest_avg_salary = A.groupby('Department')['Salary'].mean().sort_values(ascending= False).head(1)
print(highest_avg_salary)

Department
IT    62000.0
Name: Salary, dtype: float64

### Q33. Find the city with the **highest average Score**.

**Expected Output: One city name.**

In [ ]:
highest_avg_score = A.groupby('City')['Score'].mean().sort_values(ascending= False).head(1)
print(highest_avg_score)

City
Pune    87.666667
Name: Score, dtype: float64

### Q34. Calculate the total Salary paid by each Department using `sum()`.

**Expected Output: Total salary for IT, HR, and Sales.**

In [ ]:
total_salary = A.groupby('Department')['Salary'].sum()
print(total_salary)

Department
HR       196000
IT       310000
Sales    149000
Name: Salary, dtype: int64

### Q35. Calculate the average Salary for each combination of `Department` and `Gender`.

**Expected Output: Department + Gender wise average Salary.**

In [ ]:
avg_salary = A.groupby(['Department', 'Gender'])['Salary'].mean()
print(avg_salary)

Department  Gender
HR          F         50000.0
            M         46000.0
IT          F         58000.0
            M         63000.0
Sales       F         49500.0
            M         50000.0
Name: Salary, dtype: float64

# Part E — Pivot Table & Crosstab

### Q36. Create a pivot table showing **mean Salary by Department and City** using `pivot_table()`.

**Expected Output: Departments as rows, Cities as columns, mean Salary as values.**

In [ ]:
A.pivot_table(values= "Salary", index= "Department", columns= "City", aggfunc= "mean")

City         Bhopal    Delhi   Mumbai     Pune
Department
HR          46000.0  52000.0  48000.0  50000.0
IT          70000.0  55000.0  65000.0  60000.0
Sales           NaN  49500.0  50000.0      NaN

### Q37. Create a pivot table showing **mean Score by Department and Gender**.

**Expected Output: Departments as rows, Gender as columns, mean Score as values.**

In [ ]:

A.pivot_table(values= "Score", index= "Department", columns= "Gender", aggfunc= "mean")

Gender              F     M
Department
HR          87.333333  73.0
IT          87.000000  89.5
Sales       84.000000  84.0

### Q38. Create a crosstab showing the frequency of `Department` vs `City`.

**Expected Output: A frequency table with departments as rows and cities as columns.**

In [ ]:
crosstab_result = pd.crosstab(A['Department'], A['City'])
print(crosstab_result)

City        Bhopal  Delhi  Mumbai  Pune
Department
HR               1      1       1     1
IT               1      1       1     2
Sales            0      2       1     0

### Q39. Create a crosstab showing `Department` vs `Gender`.

**Expected Output: Count of M/F employees in each department.**

In [ ]:
crosstab_result = pd.crosstab(A['Department'], A['Gender'])
print(crosstab_result)

Gender      F  M
Department
HR          3  1
IT          1  4
Sales       2  1

# Q40. ⭐ Final Practical Challenge

Using the same 8-column DataFrame:

1. Sort employees by `Salary` from highest to lowest.
2. Find the average Salary of each Department.
3. Find the Department with the highest average Salary.
4. Find the average Score by City.
5. Create a pivot table of mean Salary by Department and City.
6. Create a crosstab of Department vs Gender.

**Expected Result:** A small analysis report containing all six results.

In [ ]:
# print("Original DataFrame")
# print(A)

A = A.sort_values(by= 'Salary', ascending= False)
print(A)

avg_salary = A.groupby('Department')['Salary'].mean()
print("\nAverage salary of each department:")
print(avg_salary)

highest_avg_salary= A.groupby('Department')['Salary'].mean().idxmax()
print("\nDepartment with highest average salary:")
print(highest_avg_salary)

avg_score = A.groupby('City')['Score'].mean()
print("\nAverage score by city:")
print(avg_score)

pivot_salary = A.pivot_table(values= 'Salary', index= 'Department', columns='City', aggfunc= 'mean')
print("\nPivot table: Average Salary by Department and City")
print(pivot_salary)

crosstab_result = pd.crosstab(A['Department'], A['Gender'])
print("\nCrosstab: Employees by Department and Gender")
print(crosstab_result)

   Department Employee  Salary  Age    City  Experience  Score Gender
4          IT    Karan   70000   32  Bhopal           8     95      M
10         IT    Rahul   65000   35  Mumbai          10     90      M
2          IT     Ravi   62000   29    Pune           5     91      M
7          IT    Pooja   58000   26    Pune           3     87      F
0          IT     Aman   55000   24   Delhi           2     82      M
9       Sales   Anjali   54000   31   Delhi           7     92      F
5          HR   Simran   52000   30   Delhi           6     89      F
6       Sales    Arjun   50000   28  Mumbai           5     84      M
11         HR     Isha   50000   26    Pune           3     85      F
1          HR     Neha   48000   27  Mumbai           4     88      F
8          HR    Mohit   46000   23  Bhopal           1     73      M
3       Sales    Priya   45000   25   Delhi           3     76      F

Average salary of each department:
Department
HR       49000.000000
IT       62000.000000
Sales    49666.666667
Name: Salary, dtype: float64

Department with highest average salary:
IT

Average score by city:
City
Bhopal    84.000000
Delhi     84.750000
Mumbai    87.333333
Pune      87.666667
Name: Score, dtype: float64

Pivot table: Average Salary by Department and City
City         Bhopal    Delhi   Mumbai     Pune
Department
HR          46000.0  52000.0  48000.0  50000.0
IT          70000.0  55000.0  65000.0  60000.0
Sales           NaN  49500.0  50000.0      NaN

Crosstab: Employees by Department and Gender
Gender      F  M
Department
HR          3  1
IT          1  4
Sales       2  1

# ⭐ Bonus Challenge

Using the main DataFrame:

- Find the employee with the highest Salary.
- Find the employee with the highest Score.
- Find the Department with the highest total Salary.
- Find the City with the most employees.
- Find the average Experience of each Department.

Try to solve these using `groupby()`, `agg()`, sorting, and filtering.

In [ ]:
print("Employee with highest salary:")
print(A.groupby('Employee')['Salary'].max().idxmax())

print("\nEmployee with highest score:")
print(A.groupby('Employee')['Score'].max().idxmax())

print("\nDepartment with the highest total salary:")
print(A.groupby('Department')['Salary'].sum().idxmax())

print("\nCity with most employees:")
print(A.groupby('City')['Employee'].count().idxmax())

print("\nAverage experience of each department:")
print(A.groupby('Department')['Experience'].mean())

Employee with highest salary:
Karan

Employee with highest score:
Karan

Department with the highest total salary:
IT

City with most employees:
Delhi

Average experience of each department:
Department
HR       3.5
IT       5.6
Sales    5.0
Name: Experience, dtype: float64