<a href="https://colab.research.google.com/github/riddhimach24-dev/Data_Science/blob/main/02_Pandas/Assignments/sheet1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas Assignment (Class 1 & 2)

### Topics Covered
- Importing Pandas
- Series
- DataFrame
- DataFrame Creation
- head(), tail(), info(), describe()
- Column Selection
- loc & iloc
- index, columns, values
- rename()
- set_index()

**Instructions:** Solve every question in the code cell below it.

## Q1. Import the **pandas** library using the alias `pd`.

In [ ]:
import pandas as pd

## Q2. Create a **Series** containing: 10, 20, 30, 40, 50.

In [ ]:
a = [10,20,30,40,50]
pd.Series(a)

0    10
1    20
2    30
3    40
4    50
dtype: int64

## Q3. Create a DataFrame having columns **Name**, **Age**, and **City** with at least 5 records.

In [ ]:
a = {
    'Name':['Aastha','Ayushi','Diya','Ritika','Sameeksha'],
    'Age':[20, 19, 24, 28, 17],
    'City':['Delhi','Bombay','Pune','Noida','Banglore']
}
b = pd.DataFrame(a)
print(b)

        Name  Age      City
0     Aastha   20     Delhi
1     Ayushi   19    Bombay
2       Diya   24      Pune
3     Ritika   28     Noida
4  Sameeksha   17  Banglore

## Q4. Create a DataFrame using a NumPy array of your choice.

In [ ]:
import numpy as np
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
pd.DataFrame(arr, columns = ['A','B','C'])

    A   B   C
0  10  20  30
1  40  50  60
2  70  80  90

## Q5. Display the first **3 rows** of a DataFrame using `head()`.

In [ ]:
print(b)
b.head(3)

        Name  Age      City
0     Aastha   20     Delhi
1     Ayushi   19    Bombay
2       Diya   24      Pune
3     Ritika   28     Noida
4  Sameeksha   17  Banglore

     Name  Age    City
0  Aastha   20   Delhi
1  Ayushi   19  Bombay
2    Diya   24    Pune

## Q6. Display the last **2 rows** using `tail()`.

In [ ]:
b.tail(2)

        Name  Age      City
3     Ritika   28     Noida
4  Sameeksha   17  Banglore

## Q7. Display the information of a DataFrame using `info()`.

In [ ]:
b.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   City    5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

## Q8. Display the statistical summary using `describe()`.

In [ ]:
b.describe()

             Age
count   5.000000
mean   21.600000
std     4.393177
min    17.000000
25%    19.000000
50%    20.000000
75%    24.000000
max    28.000000

## Q9. Select only the **Name** column.

In [ ]:
b['Name']

0       Aastha
1       Ayushi
2         Diya
3       Ritika
4    Sameeksha
Name: Name, dtype: object

## Q10. Select the **Name** and **Age** columns together.

In [ ]:
b[['Name','Age']]

        Name  Age
0     Aastha   20
1     Ayushi   19
2       Diya   24
3     Ritika   28
4  Sameeksha   17

## Q11. Using `loc`, print the first three rows.

In [ ]:
b.loc[0:2]

     Name  Age    City
0  Aastha   20   Delhi
1  Ayushi   19  Bombay
2    Diya   24    Pune

## Q12. Using `iloc`, print rows 1 to 3 and the first two columns.

In [ ]:
b.iloc[0:3,0:2]

     Name  Age
0  Aastha   20
1  Ayushi   19
2    Diya   24

## Q13. Print the DataFrame's `index`, `columns`, and `values`.

In [ ]:
print(b.index)
print(b.columns)
print(b.values)

RangeIndex(start=0, stop=5, step=1)
Index(['Name', 'Age', 'City'], dtype='object')
[['Aastha' 20 'Delhi']
 ['Ayushi' 19 'Bombay']
 ['Diya' 24 'Pune']
 ['Ritika' 28 'Noida']
 ['Sameeksha' 17 'Banglore']]

## Q14. Rename the column **Name** to **Student_Name**.

In [ ]:
c = b.rename(columns = {'Name':'Student_Name'})
print(c)

  Student_Name  Age      City
0       Aastha   20     Delhi
1       Ayushi   19    Bombay
2         Diya   24      Pune
3       Ritika   28     Noida
4    Sameeksha   17  Banglore

## Q15. Set the **Name** column as the index of the DataFrame.

In [ ]:
b.set_index('Name', inplace = True)
print(b)

           Age      City
Name
Aastha      20     Delhi
Ayushi      19    Bombay
Diya        24      Pune
Ritika      28     Noida
Sameeksha   17  Banglore